datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientId
            client-secret: clientSecret
          facebook:
            client-id: clientId
            client-secret: clientSecret
custom:
  oauth2:
    kakao:
      client-id: clientId