spring:
  profiles:
    active: local
server:
  port: 80

# @Value 테스트 프로퍼티 값
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

# @ConfigurationProperties 테스트 프로퍼티 값
fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082