spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #    url: jdbc:mysql://
    #    username:
    #    password:
    #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientId
            client-secret: clientSecret
          facebook:
            client-id: clientId
            client-secret: clientSecret
custom:
  oauth2:
    kakao:
      client-id: clientId