spring:
  profiles:
    active: local

server:
  port: 80

# @Value 테스트 프로퍼티 값
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

# @ConfigurationProperties 테스트 프로퍼티 값
fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green

fruit-data:
#  colorname: blue
#  colorName: blue
#  color-name: blue
  color_name: blue

---
spring:
  profiles: local
  h2:
    console:
      enabled: true
# H2 메모리 DB를 사용하기 위한 설정
datasource:
  url: jdbc:h2:mem:testdb

server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082