datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          facebook:
            client-id:
            client-secret:
custom:
        oauth2:
          kakao:
            client-id: